# Generated by Django 2.2.7 on 2019-11-30 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя ответственного за микросервис')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия ответственного за микросервис')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность ответственного за микросервис')),
            ],
            options={
                'verbose_name': 'Ответственный',
                'verbose_name_plural': 'Ответственные',
            },
        ),
        migrations.CreateModel(
            name='Microservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название микросервиса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание микросервиса')),
                ('status', models.CharField(choices=[('idea', 'Идея'), ('design', 'Проектирование'), ('development', 'Разработка'), ('text', 'Тестирование'), ('revision', 'В доработке'), ('support', 'Поддержка')], default='development', max_length=32, verbose_name='Статус микросервиса')),
                ('external_id', models.IntegerField(unique=True, verbose_name='ID микросервиса')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Время начала работы над микросервисом')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения работы над микросервисом')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservices.Author', verbose_name='Ответственный за микросервис')),
            ],
            options={
                'verbose_name': 'Микросервис',
                'verbose_name_plural': 'Микросервисы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тега')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание тега')),
                ('microservice', models.ManyToManyField(blank=True, to='microservices.Microservice')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('connection', models.CharField(choices=[('>', '>'), ('<', '<'), ('=', '=')], default='>', max_length=32, verbose_name='Направление связи')),
                ('first_microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_microservices', to='microservices.Microservice', verbose_name='Первый микросервис в паре')),
                ('second_microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_microservices', to='microservices.Microservice', verbose_name='Второй микросервис в паре')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
