# Generated by Django 2.2.7 on 2019-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0002_auto_20191130_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Время завершения работы над микросервисом'),
        ),
        migrations.AlterField(
            model_name='microservice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Время начала работы над микросервисом'),
        ),
        migrations.AlterField(
            model_name='microservice',
            name='status',
            field=models.CharField(choices=[('idea', 'Идея'), ('design', 'Проектирование'), ('development', 'Разработка'), ('text', 'Тестирование'), ('revision', 'В доработке'), ('support', 'Поддержка'), ('closed', 'Закрыто')], default='development', max_length=32, verbose_name='Статус микросервиса'),
        ),
    ]
